#include<iostream>
#include<bits/stdc++.h>
using namespace std;
int main()
{
    int i,n,it=1,it1,val,init1,val1,f=1,j,start,val2,val3=2,start1,init,count=1,count1;
    cin>>n;
    val1=n;
    start=n;
    init1=n-2;
    start1=n-1;
    for(i=1;i<=n-2;i++)
    {
        val=val1;
        it1=it;
        for(j=1;j<=start;j++)
        {
            f=1;
            while(it1!=0)
            {
                cout<<val;
                f=0;
                it1--;
            }
            if(f==1 && it1==0)
            {
                val--;
                cout<<val;
            }
        }
        it1=it;
        init=init1;
        val2=val3;
        for(j=1;j<=start1;j++)
        {
            if(init!=0)
            {
                cout<<val2;
                val2++;
                init--;
            }
            else
            {
                while(it1!=0)
                {
                    cout<<val2;
                    it1--;
                }
            }
        }
        init1--;
        it++;
        val1--;
        start--;
        start1--;
        cout<<"\n";
    }
    for(i=1;i<=n-1;i++)
    {
        cout<<"2";
    }
    cout<<"1";
    for(i=1;i<=n-1;i++)
    {
        cout<<"2";
    }
    cout<<"\n";
    start=3;
    val1=3;
    it=n-2;
    f=1;
    val3=2;
    start1=2;
    for(i=1;i<=n-2;i++)
    {
        val=val1;
        it1=it;
        for(j=1;j<=start;j++)
        {
            f=1;
            while(it1!=0)
            {
                cout<<val;
                f=0;
                it1--;
            }
            if(f==1 && it1==0)
            {
                val--;
                cout<<val;
            }
        }
        val2=val3;
        it1=it;
        count1=count;
        for(j=1;j<=start1;j++)
        {
            if(count1!=0)
            {
                cout<<val2;
                val2++;
                count1--;
            }
            else
            {
                while(it1!=0)
                {
                    cout<<val2;
                    it1--;
                }
            }
        }
        count++;
        start1++;
        start++;
        it--;
        val1++;
        cout<<"\n";
    }
    return 0;
}
